#!/usr/bin/env python3
import time 
import skilstak.colors as c

def hello():
    print(c.red + "hello world")



if __name__ == "__main__":
    for count in range(5):
        hello()
        time.sleep(0.5)
